FROM node:24-alpine AS base

WORKDIR /app

RUN corepack enable


FROM base AS builder

COPY . .

RUN CI=true pnpm turbo prune @docflow/worker --docker
RUN cp tsconfig.base.json out/full/tsconfig.base.json

FROM base AS installer

COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/pnpm-lock.yaml ./pnpm-lock.yaml

RUN pnpm install --frozen-lockfile

COPY --from=builder /app/out/full/ .

RUN pnpm turbo build --filter=@docflow/worker


FROM base AS runner

COPY --from=installer /app/ .

CMD ["pnpm", "--filter", "@docflow/worker", "dev"]